### ISSUE TITLE
Create database

### ISSUE THREAD

**Issue by loadevent** [loadevent/CountryClub-Web#4]
- [ ] create database tables
- [ ] create relationships between tables
- [ ] populate with dummy data
