### ISSUE TITLE
Create web application structure

### ISSUE THREAD

**Issue by loadevent** [loadevent/CountryClub-Web#6]
- [ ] link application to country club database using entity framework
- [ ] create models from database entity framework 
- [ ] add controllers with entity framework layout
- [ ] create views
