### ISSUE TITLE
App layout

### ISSUE THREAD

**Issue by loadevent** [loadevent/CountryClub-Web#7]
- [ ] create css and js files
- [ ] create layout for admin view(s)
- [ ] create layout for provider view(s)
- [ ] create layout for other view(s)
- [ ] create a layout for login view
- [ ] add a login view
